### PR TITLE
Make some tests use deterministic torch algorithms

### PR DESCRIPTION
**Pull request by RaulPPelaez**
This fixes some tests not passing on some architectures due to numerical inaccuraccies (at least on my machine).

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
@mikemhenry @raimis , try the GPU runner here please.

**Comment by mikemhenry** [comment]
Tests running here https://github.com/openmm/NNPOps/actions/runs/5660607367

**Comment by mikemhenry** [comment]
```
RuntimeError: Deterministic behavior was enabled with either `torch.use_deterministic_algorithms(True)` or `at::Context::setDeterministicAlgorithms(true)`, but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility
```

Looks like I need to add this to the runner

**Comment by mikemhenry** [comment]
New test here https://github.com/openmm/NNPOps/actions/runs/5661251365

**Comment by mikemhenry** [comment]
Tests pass!

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
I setup auto-merge, review required, and status checks. Let me know if that causes any issues @RaulPPelaez @raimis

**Pull request merged**
