### PR TITLE
Use args when calling self.aev_computer

### PR DESCRIPTION
**Pull request by lohedges**
This PR allows the use of a forward hook on the internal AEVComputer of ANI models when using OptmizedTorchANI via TorchScript. See aiqm/torchani#649 for details.

### CODE REVIEW

**Comment by peastman** [comment]
Does this introduce any compatibility issues we need to be aware of, such as only working with newer versions of TorchANI?

**Comment by lohedges** [comment]
I don't think so, I've checked back to version 1.0.0  of TorchANI and the signature of `AEVComputer.forward` is identical (although missing type hinting). Older versions, e.g. the original 0.1 release, are missing the `cell` and `pbc` kwargs, but I doubt you support those given that the oldest version of TorchANI on conda-forge is 2.2.

Just to note that while the PR linked to above won't (yet) be merged due to a code freeze, this fix is independent of it, i.e. it allows you to use an AEVComputer forward hook with OptimizedTorchANI without requiring the fix to TorchANI itself.

**Review by RaulPPelaez — APPROVED** [review]

**Comment by peastman** [comment]
@RaulPPelaez any idea what's going on with CI?

**Comment by peastman** [comment]
I checked and the rules listed there are correct.  The problem is that none of the CI builds have run.  And there's no option to retrigger them.  Let me try making a trivial change to the file and see if that gets it working.

**Comment by peastman** [comment]
Look like they're running now.

**Comment by peastman** [comment]
One build is failing with the dreaded `[Errno 28] No space left on device'`.  It's clearly not related to this change, so I'm ok with merging it.  I'm currently dealing with that same error in [trying to do a new OpenMM dev build](https://github.com/conda-forge/openmm-feedstock/pull/132).

**Comment by lohedges** [comment]
Many thanks for looking at this so quickly.

**Pull request merged**
