### PR TITLE
Added option to use tanh activation

### PR DESCRIPTION
**Pull request by peastman**
Addresses the requirements of #21.  @brookehus and @nec4 can you confirm this meets your needs?

### CODE REVIEW

**Comment by brookehus** [comment]
@nec4 can you look at this when you have time?

**Comment by nec4** [comment]
Of course - taking a look now!

**Review by nec4 — APPROVED** [review]
This looks good to me! - though I have not run the tests on my local machine. I  have only double checked the forward pass and derivative calculation (the rest is just modifying input arguments and adding a duplicate test using Tanh instead of SSP if I understand correctly). If you would like me to run the tests, I can setup an environment on my end.

**Comment by peastman** [comment]
Thanks!  I already ran the tests.  Just wanted to make sure this has all the features you need.

**Pull request merged**
