### PR TITLE
Update to TorchANI 2.2.2

### PR DESCRIPTION
**Pull request by raimis**
- [x] Update to TorchANI 2.2.2 (https://github.com/aiqm/torchani/issues/598)
- [x] Update to PyTorch 1.10
- [x] Fix the API changes
- [x] Update CI versions

### CODE REVIEW

**Comment by raimis** [comment]
One more issue: https://github.com/aiqm/torchani/issues/598#issuecomment-959004422

**Comment by raimis** [comment]
Waiting for TorchANI 2.2.2 (https://github.com/conda-forge/torchani-feedstock/pull/3)!

**Comment by yueyericardo** [comment]
@raimis TorchANI 2.2.2 is ready

**Comment by raimis** [comment]
@peastman could you review?

**Review by peastman — APPROVED** [review]
Looks good!

**Pull request merged**
